In [2]:
l = [23, 11, 34, 56, 23, 11]
l

[23, 11, 34, 56, 23, 11]

In [3]:
set_l = set(l)
len(set_l)

4

In [4]:
set_l

{11, 23, 34, 56}

In [3]:
import pandas
l = [23, 11, 34, 56, 23, 11]

ser = pandas.Series(l)

In [8]:
l

[23, 11, 34, 56, 23, 11]

In [9]:
ser

0    23
1    11
2    34
3    56
4    23
5    11
dtype: int64

In [10]:
ser[5]

11

In [12]:
ser['A']

34

In [4]:
values = [23,11,34,56,23,11]
labels = ['A','B','C','D','E','F']
df = pandas.DataFrame({"Name":labels, "Value": values})

NameError: name 'pd' is not defined

In [15]:
df

  Name  Value
0    A     23
1    B     11
2    C     34
3    D     56
4    E     23
5    F     11

In [13]:
values = [23,11,34,56,23,11]
labels = ['A', 'B', 'C', 'D', 'E', 'F']
df = pandas.DataFrame({"Name":labels, "Value": values})
df

  Name  Value
0    A     23
1    B     11
2    C     34
3    D     56
4    E     23
5    F     11

In [12]:
df.iloc[3,1]

56

In [2]:
df.loc[0]

NameError: name 'df' is not defined