In [2]:
import pandas as pd
dict = {"Key":["one","two","three"],"Value":[1,2,3]}
df1 = pd.DataFrame(dict)
df1

     Key  Value
0    one      1
1    two      2
2  three      3

In [9]:
df2=df1.iloc[[1,1]]
df2

   Key  Value
1  two      2
1  two      2

In [10]:
type(df2)

pandas.core.frame.DataFrame

In [12]:
df3= df1.iloc[1,1]
df3

2

In [13]:
type(df3)

numpy.int64

In [24]:
import json
with open("iris.json","r") as file:
    
    k = json.load(file)
type(k)

list

In [31]:
import math
y = math.nan
type(y)

float

In [35]:
s = ['C','A','B','A']
t = [2,3,2,3]
df4 = pd.DataFrame({"Name":s,"Value":t})
df4

  Name  Value
0    C      2
1    A      3
2    B      2
3    A      3

In [36]:
df5 = df4.drop_duplicates()
df5

  Name  Value
0    C      2
1    A      3
2    B      2

In [37]:
len(df5)

3

In [39]:
I = [35,21,10,55]
ser = pd.Series(I, index = ["D", 'A', 'B', 'C'])
ser

D    35
A    21
B    10
C    55
dtype: int64

In [44]:
sorted_ser = ser.sort_index()
sorted_ser

A    21
B    10
C    55
D    35
dtype: int64

In [45]:
sorted_ser[0]

/tmp/ipykernel_539/695436071.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sorted_ser[0]

21